services:
  counter-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: staff-counter-bot
    container_name: counter-bot
    volumes:
      - ./src/db/database.sqlite:/app/src/db/database.sqlite
    restart: unless-stopped